//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fsxget.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Deutsch {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Deutsch() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fsxget.lang.Deutsch", typeof(Deutsch).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Über FSXGET.
        /// </summary>
        internal static string Form_Main_ContextMenu_About {
            get {
                return ResourceManager.GetString("Form_Main_ContextMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer Aircraft Pfad &amp;löschen.
        /// </summary>
        internal static string Form_Main_ContextMenu_ClearPath {
            get {
                return ResourceManager.GetString("Form_Main_ContextMenu_ClearPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Earth &amp;KML Datei erzeugen.
        /// </summary>
        internal static string Form_Main_ContextMenu_CreateKmlFile {
            get {
                return ResourceManager.GetString("Form_Main_ContextMenu_CreateKmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker &amp;aktivieren.
        /// </summary>
        internal static string Form_Main_ContextMenu_Enable {
            get {
                return ResourceManager.GetString("Form_Main_ContextMenu_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Beenden.
        /// </summary>
        internal static string Form_Main_ContextMenu_Exit {
            get {
                return ResourceManager.GetString("Form_Main_ContextMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Optionen.
        /// </summary>
        internal static string Form_Main_ContextMenu_Options {
            get {
                return ResourceManager.GetString("Form_Main_ContextMenu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Pause.
        /// </summary>
        internal static string Form_Main_ContextMenu_Pause {
            get {
                return ResourceManager.GetString("Form_Main_ContextMenu_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Earth Objekte &amp;neu erzeugen.
        /// </summary>
        internal static string Form_Main_ContextMenu_RecreateObjects {
            get {
                return ResourceManager.GetString("Form_Main_ContextMenu_RecreateObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft &amp;Flight Simulator X starten.
        /// </summary>
        internal static string Form_Main_ContextMenu_RunFSX {
            get {
                return ResourceManager.GetString("Form_Main_ContextMenu_RunFSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Google Earth 4 starten.
        /// </summary>
        internal static string Form_Main_ContextMenu_RunGE {
            get {
                return ResourceManager.GetString("Form_Main_ContextMenu_RunGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei ändern der Frequenz ist ein Fehler aufgetreten! Die Frequenz wurde nicht geändert..
        /// </summary>
        internal static string Kml_SetFreq_Error {
            get {
                return ResourceManager.GetString("Kml_SetFreq_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Ändern der Frequenz wurde gestartet..
        /// </summary>
        internal static string Kml_SetFreq_Ok {
            get {
                return ResourceManager.GetString("Kml_SetFreq_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieses Programm benötigt Windows XP SP2 oder Windows Server 2003 mit der aktuellsten Version des .NET Framework! Die Anwendung wird beendet..
        /// </summary>
        internal static string System_HTTPListenerNotSupported {
            get {
                return ResourceManager.GetString("System_HTTPListenerNotSupported", resourceCulture);
            }
        }
    }
}
