//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fsxget.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fsxget.lang.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About FSXGET.
        /// </summary>
        internal static string Form_Main_ContextMenu_About {
            get {
                return ResourceManager.GetString("Form_Main_ContextMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear User Aircraft Path.
        /// </summary>
        internal static string Form_Main_ContextMenu_ClearPath {
            get {
                return ResourceManager.GetString("Form_Main_ContextMenu_ClearPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Google Earth &amp;KML File.
        /// </summary>
        internal static string Form_Main_ContextMenu_CreateKmlFile {
            get {
                return ResourceManager.GetString("Form_Main_ContextMenu_CreateKmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Enable Tracker.
        /// </summary>
        internal static string Form_Main_ContextMenu_Enable {
            get {
                return ResourceManager.GetString("Form_Main_ContextMenu_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string Form_Main_ContextMenu_Exit {
            get {
                return ResourceManager.GetString("Form_Main_ContextMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options.
        /// </summary>
        internal static string Form_Main_ContextMenu_Options {
            get {
                return ResourceManager.GetString("Form_Main_ContextMenu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Pause.
        /// </summary>
        internal static string Form_Main_ContextMenu_Pause {
            get {
                return ResourceManager.GetString("Form_Main_ContextMenu_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Recreate Google Earth Objects.
        /// </summary>
        internal static string Form_Main_ContextMenu_RecreateObjects {
            get {
                return ResourceManager.GetString("Form_Main_ContextMenu_RecreateObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Microsoft &amp;Flight Simulator X.
        /// </summary>
        internal static string Form_Main_ContextMenu_RunFSX {
            get {
                return ResourceManager.GetString("Form_Main_ContextMenu_RunFSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run &amp;Google Earth 4.
        /// </summary>
        internal static string Form_Main_ContextMenu_RunGE {
            get {
                return ResourceManager.GetString("Form_Main_ContextMenu_RunGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to change the frequency! The Frequency has not been changed..
        /// </summary>
        internal static string Kml_SetFreq_Error {
            get {
                return ResourceManager.GetString("Kml_SetFreq_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The frequency change has been successfully initiated..
        /// </summary>
        internal static string Kml_SetFreq_Ok {
            get {
                return ResourceManager.GetString("Kml_SetFreq_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program requires Windows XP SP2 or Windows Server 2003 with the latest version of the .NET framework installed! The application will exit now..
        /// </summary>
        internal static string System_HTTPListenerNotSupported {
            get {
                return ResourceManager.GetString("System_HTTPListenerNotSupported", resourceCulture);
            }
        }
    }
}
